name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias Linux
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y libsdl2-dev libgl-dev mingw-w64

      - name: Descargar stb_image.h
        run: |
          curl -L https://raw.githubusercontent.com/nothings/stb/master/stb_image.h \
               -o csrc/stb_image.h

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
            build-win
          key: cmake-${{ hashFiles('CMakeLists.txt') }}

      - name: Build Linux x64
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Build Windows x64
        run: |
          cmake -B build-win \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build-win

      - uses: actions/upload-artifact@v4
        with:
          name: openstrike-builds
          path: |
            build/openstrike
            build-win/openstrike.exe
